distribution: Ubuntu
release: trusty
venv: 'cloudify/test_venv/env'
python_path: '/usr/bin/python'
base_modules:
    plugins_common: https://github.com/geokala/cloudify-plugins-common/archive/ipv6mods.tar.gz
    rest_client: https://github.com/cloudify-cosmo/cloudify-rest-client/archive/3.2m8.tar.gz
    script_plugin: https://github.com/cloudify-cosmo/cloudify-script-plugin/archive/1.2m8.tar.gz
    diamond_plugin: https://github.com/cloudify-cosmo/cloudify-diamond-plugin/archive/1.2m8.tar.gz
management_modules_version: ipv6mods
output_tar: Ubuntu-trusty-agent.tar.gz
keep_venv: false
